apiVersion: v1
kind: Service
metadata:
  name: {{ include "idman-ip.fullname" . }}
  labels:
{{ include "idman-ip.labels" . | indent 4 }}
{{ include "cenm.labels" . | indent 4 }}
spec:
# we need Local policy and healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: main
    - port: {{ .Values.shell.sshdPort }}
      targetPort: {{ .Values.shell.sshdPort }}
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: idman
    app.kubernetes.io/instance: idman
{{ include "cenm.labels" . | indent 4 }}

