{{- $DATE := ( include "currentDateTime" . ) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notary-conf-{{ $DATE }}
  labels:
{{ include "notary.labels" . | indent 4 }}
data:
  run.sh: |+
{{ tpl (.Files.Get "files/run.sh") . | indent 4 }}

  notary-initial-registration.sh: |+
{{ tpl (.Files.Get "files/notary-initial-registration.sh") . | indent 4 }}

  create-network-parameters-file.sh: |+
{{ tpl (.Files.Get "files/create-network-parameters-file.sh") . | indent 4 }}

  notary.conf: |+
{{ tpl (.Files.Get "files/notary.conf") . | indent 4 }}

