apiVersion: v1
kind: Service
metadata:
  name: {{ include "farm.fullname" . }}
  labels:
    {{- include "farm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "farm.selectorLabels" . | nindent 4 }}
