{{- $DATE := ( include "currentDateTime" . ) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nmap-conf-{{ $DATE }}
  labels:
{{ include "nmap.labels" . | indent 4 }}
data:
  run.sh: |+
{{ tpl (.Files.Get "files/run.sh") . | indent 4 }}

  set-network-parameters.sh: |+
{{ tpl (.Files.Get "files/set-network-parameters.sh") . | indent 4 }}

  nmap.conf: |+
{{ tpl (.Files.Get "files/nmap.conf") . | indent 4 }}

  network-parameters-update-example.conf: |+
{{ tpl (.Files.Get "files/network-parameters-update-example.conf") . | indent 4 }}
