---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-nmap-bin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-nmap-etc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNmapEtc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-nmap-logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNmapLogs }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-nmap-h2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNmapH2 }}
