apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmap.fullname" . }}
  labels:
{{ include "nmap.labels" . | indent 4 }}
{{ include "cenm.labels" . | indent 4 }}
spec:
# we need Local policy and healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.shell.sshdPort }}
      targetPort: {{ .Values.shell.sshdPort }}
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "nmap.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmap.fullname" . }}-internal
  labels:
{{ include "nmap.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.serviceInternal.port }}
      targetPort: {{ .Values.serviceInternal.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nmap.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
