apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gateway.fullname" . }}-job
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "5"
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-check-gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gatewayImage.repository }}:{{ .Values.gatewayImage.tag }}"
          imagePullPolicy: {{ .Values.gatewayImage.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |-
            echo Probing {{ .Values.prefix }}-gateway port {{ .Values.gatewayPort }}
            until nc -w 5 -vz {{ .Values.prefix }}-gateway {{ .Values.gatewayPort }} > /dev/null 2>&1
            do
              echo "Connect to {{ .Values.prefix }}-gateway port {{ .Values.gatewayPort }} (tcp) failed: Connection refused"
            done
            echo "Connection {{ .Values.prefix }}-gateway port {{ .Values.gatewayPort }} successful"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-check-auth
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gatewayImage.repository }}:{{ .Values.gatewayImage.tag }}"
          imagePullPolicy: {{ .Values.gatewayImage.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |-
            echo Probing {{ .Values.prefix }}-auth port {{ .Values.authPort }}
            until nc -w 5 -vz {{ .Values.prefix }}-auth {{ .Values.authPort }} > /dev/null 2>&1
            do
              echo "Connect to {{ .Values.prefix }}-auth port {{ .Values.authPort }} (tcp) failed: Connection refused"
            done
            echo "Connection {{ .Values.prefix }}-auth port {{ .Values.authPort }} successful"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gatewayImage.repository }}:{{ .Values.gatewayImage.tag }}"
          imagePullPolicy: {{ .Values.gatewayImage.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |-
            pwd
            cd /opt/cenm/CM-FILES/
            ls -alR
            ./setupAuth.sh {{ .Values.prefix }}-gateway {{ .Values.gatewayPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: pki-certs-keys
            mountPath: /opt/cenm/DATA
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/setupAuth.sh
            subPath: setupAuth.sh
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/ca-signers.json
            subPath: ca-signers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/configuration-maintainers.json
            subPath: configuration-maintainers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/configuration-readers.json
            subPath: configuration-readers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/network-maintainers.json
            subPath: network-maintainers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/network-operation-readers.json
            subPath: network-operation-readers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/network-operators.json
            subPath: network-operators.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/nonca-signers.json
            subPath: nonca-signers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/CASigner.json
            subPath: CASigner.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/ConfigurationMaintainer.json
            subPath: ConfigurationMaintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/ConfigurationReader.json
            subPath: ConfigurationReader.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/NetworkMaintainer.json
            subPath: NetworkMaintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/NetworkOperationsReader.json
            subPath: NetworkOperationsReader.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/NetworkOperator.json
            subPath: NetworkOperator.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/NonCASigner.json
            subPath: NonCASigner.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/business-reader.json
            subPath: business-reader.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/ca-signer.json
            subPath: ca-signer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/config-maintainer.json
            subPath: config-maintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/config-reader.json
            subPath: config-reader.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/network-maintainer.json
            subPath: network-maintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/network-operator.json
            subPath: network-operator.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/nonca-signer.json
            subPath: nonca-signer.json
      restartPolicy: OnFailure
      volumes:
        - name: pki-certs-keys
          persistentVolumeClaim:
            claimName: {{ .Values.prefix }}-pki-certs-keys
        - name: gateway-conf
          configMap:
            name: {{ .Values.prefix }}-gateway-conf
            defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
