apiVersion: v1
kind: Service
metadata:
  name: {{ include "signer.fullname" . }}
  labels:
{{ include "signer.labels" . | indent 4 }}
{{ include "cenm.labels" . | indent 4 }}
spec:
# we need Local policy and healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.serviceSsh.port }}
      targetPort: {{ .Values.serviceSsh.port }}
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "signer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
