apiVersion: v1
kind: Service
metadata:
  name: {{ include "signer.fullname" . }}
  labels:
    {{- include "signer.labels" . | nindent 4 }}
spec:
  {{- if .Values.healthCheckNodePort }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
  {{- end }}
  {{- if .Values.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy }}
  {{- end }}
  type: {{ .Values.adminListener.type }}
  ports:
    - port: {{ .Values.adminListener.port }}
      targetPort: {{ .Values.adminListener.port }}
      protocol: TCP
      name: adminlistener
  selector:
    {{- include "signer.selectorLabels" . | nindent 4 }}
