apiVersion: v1
kind: Namespace
metadata:
  name: cenm

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cenm
  name: all-in-cenm-namespace
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cenm
  name: everything-in-cenm
roleRef:
  kind: Role
  name: all-in-cenm-namespace
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "[your-azure-group-id]" # use correct Azure group
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cenm
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
allowVolumeExpansion: true
