# Default values for nmap.

nameOverride: ""
fullnameOverride: ""

bashDebug: false

dockerImage:
  name: corda/enterprise-networkmap
  tag: 1.2-zulu-openjdk8u242
  pullPolicy: Always

# required parameter
acceptLicense:


service:
  type: LoadBalancer
  port: 10000

serviceInternal:
  type: LoadBalancer
  port: 5050

shell:
  sshdPort: 2222
  user: nmap
  password: nmapP

# where is CENM service jar file stored
jarPath: bin

# where is CENM service configuration file stored
configPath: etc

database:
  driverClassName: "org.h2.Driver"
  url: "jdbc:h2:file:./h2/networkmap-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  user: "example-db-user"
  password: "example-db-password"
  runMigration: true

checkRevocation: true

identityManager:
  host: idman-internal
  port: 5052

revocation:
  port: 5053

sleepTimeAfterError: 120
sleepTime: 0

cordaJarMx: 1

healthCheckNodePort: 0