apiVersion: v1
kind: Service
metadata:
  name: {{ include "idman.fullname" . }}-internal
  labels:
    {{- include "idman.labels" . | nindent 4 }}
spec:
  {{- if .Values.healthCheckNodePort }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
  {{- end }}
  ports:
    - port: {{ .Values.serviceInternal.port }}
      targetPort: {{ .Values.serviceInternal.port }}
      protocol: TCP
      name: issuance
    - port: {{ .Values.serviceRevocation.port }}
      targetPort: {{ .Values.serviceRevocation.port }}
      protocol: TCP
      name: revocation
    - port: {{ .Values.adminListener.port }}
      targetPort: {{ .Values.adminListener.port }}
      protocol: TCP
      name: adminlistener
  selector:
    {{- include "idman.selectorLabels" . | nindent 4 }}
    