
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-zone-conf
  labels:
    {{ include "zone.labels" . | nindent 4 }}
data:
  run.sh: |+
    {{ tpl (.Files.Get "files/run.sh") . | nindent 4 }}

