apiVersion: v1
kind: Service
metadata:
  name: {{ include "zone.fullname" . }}
  labels:
    {{- include "zone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.listenerPort.enm }}
      targetPort: {{ .Values.listenerPort.enm }}
      protocol: TCP
      name: enm
    - port: {{ .Values.listenerPort.admin }}
      targetPort: {{ .Values.listenerPort.admin }}
      protocol: TCP
      name: admin
  selector:
    {{- include "zone.selectorLabels" . | nindent 4 }}
