
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-pki-conf
  labels:
    {{ include "pki.labels" . | nindent 4 }}
data:
  run.sh: |+
    {{ tpl (.Files.Get "files/run.sh") . | nindent 4 }}

  pki.conf: |+
    {{ tpl (.Files.Get "files/pki.conf") . | nindent 4 }}

  pki-azure.conf: |+
    {{ tpl (.Files.Get "files/pki-azure.conf") . | nindent 4 }}
