---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-hsm-libs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassShared }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeHsmLibs }}
